resolver: ./snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - cardano-db
  - cardano-db/test
  - cardano-db-sync
  - cardano-db-sync-extended

ghc-options:
  cardano-db:               -Wall -Werror -fwarn-redundant-constraints
  cardano-db-test:          -Wall -Werror -fwarn-redundant-constraints
  cardano-db-sync:          -Wall -Werror -fwarn-redundant-constraints
  cardano-db-sync-extended: -Wall -Werror -fwarn-redundant-constraints

nix:
  pure: true
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , haskell.compiler.ghc865
            , pkg-config
            , systemd.dev
            , postgresql
            ]

