resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/master/snapshots/cardano-1.25.1.yaml
compiler: ghc-8.6.5

#allow-newer: true

packages:
  - cardano-sync
  - cardano-db
  - cardano-db/test
  - cardano-db-sync
  - cardano-db-sync-extended
  - cardano-db-tool

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

ghc-options:
  cardano-sync: -Wall -Werror -fwarn-redundant-constraints -Wunused-imports
  cardano-db: -Wall -Werror -fwarn-redundant-constraints -Wunused-imports
  cardano-db-test: -Wall -Werror -fwarn-redundant-constraints -Wunused-imports
  cardano-db-sync: -Wall -Werror -fwarn-redundant-constraints -Wunused-imports
  cardano-db-sync-extended: -Wall -Werror -fwarn-redundant-constraints -Wunused-imports
  cardano-db-tool: -Wall -Werror -fwarn-redundant-constraints -Wunused-imports

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
#ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - persistent-2.11.0.1
  - persistent-postgresql-2.11.0.0
  - persistent-template-2.9.1.0

  - esqueleto-3.4.0.1

  # Compiler error 'System.Metrics.Prometheus.Http.Scrape (serveMetricsT)'
  - prometheus-2.2.2

nix:
  pure: true
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , haskell.compiler.ghc865
            , pkg-config
            , systemd.dev
            , postgresql
            ]
