resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/57fcc83702b91e0a7aecdb32c99ab1d8c1c444d0/snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - cardano-explorer-db
  - cardano-explorer-db/test
  - cardano-explorer-node
  - cardano-explorer-webapi
  - cardano-tx-submit

ghc-options:
  cardano-explorer-db:          -Wall -Werror -fwarn-redundant-constraints
  cardano-explorer-node:        -Wall -Werror -fwarn-redundant-constraints
  cardano-explorer-webapi:      -Wall -Werror -fwarn-redundant-constraints
  cardano-tx-submit:            -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - network-3.1.0.1
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.2
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1
  - text-ansi-0.1.0
  - Diff-0.4.0
  - katip-0.8.3.0
  - moo-1.2
  - gray-code-0.3.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - socks-0.6.1
  - servant-0.17
  - servant-server-0.17
  - connection-0.3.1
  - http-api-data-0.4.1.1
  - time-compat-1.9.2.2

  - git: https://github.com/input-output-hk/cardano-shell
    commit: bc3563c952d9f3635e1c76749b86b0a24f7e4b83
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 57fcc83702b91e0a7aecdb32c99ab1d8c1c444d0
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 49b347d892d82dce23eb692722649cd8a1149406
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd
      - tracer-transformers

  - git: https://github.com/input-output-hk/cardano-base
    commit: a7b403c1762a6a122a691df816c26563b7e547f8
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 318f5a1594a23aedadb3977ddd5a32230c8be4fe
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 172b49ff1b6456851f10ae18f920fbfa733be0b0
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 5f77e24c2263560ad58b9ba092c8cfed174675ae
    subdirs:
      - io-sim
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-consensus
      - typed-protocols
      - ouroboros-network-framework
      - typed-protocols-examples
