{
 "title": "explorer database",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Chain Height",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "db_block_height", "legendFormat": "DB" },
    { "expr": "remote_tip_height", "legendFormat": "Node To Client Tip" },
    {
     "expr": "cardano_node_metrics_ChainDB_blockNum_int",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "title": "blocks/minute over last 5mins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(db_block_height[5m])*60", "legendFormat": "DB" },
    { "expr": "rate(remote_tip_height[5m])*60", "legendFormat": "Node To Client Tip" },
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int[5m])*60",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "title": "TBQueue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "action_queue_length_pre", "legendFormat": "pre-read" },
    { "expr": "action_queue_length_post", "legendFormat": "post-read" },
    { "expr": "action_queue_length_post_write", "legendFormat": "post-write" }
   ]
  },
  {
   "title": "epoch vs rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(cexplorerBlockCount_count/21600)",
     "legendFormat": "epoch"
    },
    {
     "expr": "rate(cexplorerBlockCount_count[5m])",
     "legendFormat": "db blocks/sec"
    },
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int[5m])",
     "legendFormat": "node blocks/sec"
    }
   ]
  },
  {
   "title": "batches/minute, 5min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_batches_inserted[5m])*60"
    }
   ]
  },
  {
   "title": "Transactions/min, 5min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_transactions_inserted[5m])*60"
    }
   ]
  },
  {
   "title": "Complete Epochs in database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(cexplorerBlockCount_count/21600)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_block_height[5m]) / rate(db_batches_inserted[5m])",
     "legendFormat": "blocks per batch"
    },
    {
     "expr": "rate(db_transactions_inserted[5m]) / rate(db_block_height[5m])",
     "legendFormat": "tx per batch"
    },
    {
     "expr": "rate(db_transactions_inserted[5m]) / rate(db_batches_inserted[5m])",
     "legendFormat": "tx per block"
    }
   ]
  }
 ]
}