-- {-# LANGUAGE FlexibleContexts #-}
-- {-# LANGUAGE OverloadedStrings #-}
-- {-# LANGUAGE TypeApplications #-}

module Cardano.DbSync.Era.Shelley.ValidateWithdrawal where

--   validateRewardWithdrawals,
-- ) where

-- import Cardano.BM.Trace (Trace, logError)
-- import Cardano.Db (Ada (..))
-- import qualified Cardano.Db as DB
-- import Cardano.DbSync.Error (shouldAbortOnPanic)
-- import Cardano.DbSync.Util
-- import Cardano.Slotting.Slot (EpochNo (..))
-- import Control.Monad.IO.Class (MonadIO, liftIO)
-- import Control.Monad.Trans.Control (MonadBaseControl)
-- import Control.Monad.Trans.Reader (ReaderT)
-- import Data.Either (partitionEithers)
-- import Data.Fixed (Micro)
-- import qualified Data.List as List
-- import Data.Text (Text)
-- import Database.Esqueleto.Experimental (
--   SqlBackend,
--   Value (Value),
--   asc,
--   distinct,
--   from,
--   groupBy,
--   having,
--   innerJoin,
--   on,
--   orderBy,
--   select,
--   sum_,
--   table,
--   unValue,
--   val,
--   where_,
--   (:&) ((:&)),
--   (<.),
--   (==.),
--   (^.),
--  )

-- {- HLINT ignore "Fuse on/on" -}

-- -- For any stake address which has seen a withdrawal, the sum of the withdrawals for that address
-- -- should be less than or equal to the sum of the rewards for that address.
-- validateRewardWithdrawals ::
--   MonadIO m =>
--   Trace IO Text ->
--   EpochNo ->
--   DB.DbAction m ()
-- validateRewardWithdrawals trce (EpochNo epochNo) = do
--   res <- mapM validateAccounting =<< DB.queryWithdrawalAddresses
--   _bad <- queryBadWithdrawals
--   liftIO $
--     case partitionEithers res of
--       ([], _) -> pure ()
--       (xs, _) -> do
--         logError trce . mconcat $
--           [textShow epochNo, ": ", textShow (length xs), " errors, eg\n"]
--             ++ List.intersperse "\n" (map reportError xs)
--         shouldAbortOnPanic "Validation failure"

-- -- -----------------------------------------------------------------------------

-- data AddressInfo = AddressInfo
--   { aiStakeAddress :: !Text
--   , aiSumRewards :: !Ada
--   , aiSumWithdrawals :: !Ada
--   }
--   deriving (Eq, Ord, Show)

-- reportError :: AddressInfo -> Text
-- reportError ai =
--   mconcat
--     [ "  "
--     , aiStakeAddress ai
--     , " rewards are "
--     , textShow (aiSumRewards ai)
--     , " ADA and withdrawals are "
--     , textShow (aiSumWithdrawals ai)
--     , " ADA"
--     ]

-- -- For a given TxId, validate the input/output accounting.
-- validateAccounting ::
--   MonadIO m =>
--   DB.StakeAddressId ->
--   DB.DbAction m (Either AddressInfo ())
-- validateAccounting addrId = do
--   ai <- queryAddressInfo addrId
--   pure $
--     if aiSumRewards ai < aiSumWithdrawals ai
--       then Left ai
--       else Right ()

-- -- -------------------------------------------------------------------------------------------------

-- -- Get all stake addresses with have seen a withdrawal, and return them in shuffled order.

-- queryAddressInfo :: MonadIO m => DB.StakeAddressId -> DB.DbAction m AddressInfo
-- queryAddressInfo addrId = do
--   rwds <- select $ do
--     rwd <- from $ table @DB.Reward
--     where_ (rwd ^. DB.RewardAddrId ==. val addrId)
--     pure (sum_ $ rwd ^. DB.RewardAmount)
--   wdls <- select $ do
--     wdl <- from $ table @DB.Withdrawal
--     where_ (wdl ^. DB.WithdrawalAddrId ==. val addrId)
--     pure (sum_ (wdl ^. DB.WithdrawalAmount))
--   view <- select $ do
--     saddr <- from $ table @DB.StakeAddress
--     where_ (saddr ^. DB.StakeAddressId ==. val addrId)
--     pure (saddr ^. DB.StakeAddressView)
--   pure $ convert (DB.listToMaybe rwds) (DB.listToMaybe wdls) (DB.listToMaybe view)
--   where
--     convert :: Maybe (Value (Maybe Micro)) -> Maybe (Value (Maybe Micro)) -> Maybe (Value Text) -> AddressInfo
--     convert rAmount wAmount mview =
--       AddressInfo
--         { aiStakeAddress = maybe "unknown" unValue mview
--         , aiSumRewards = DB.unValueSumAda rAmount
--         , aiSumWithdrawals = DB.unValueSumAda wAmount
--         }

-- -- A stake address state is bad if sum rewards < sum withdrawals
-- queryBadWithdrawals :: MonadIO m => DB.DbAction m [AddressInfo]
-- queryBadWithdrawals = do
--   res <- select $ do
--     (rwd :& sa :& wdrl) <-
--       from
--         $ table @DB.Reward
--           `innerJoin` table @DB.StakeAddress
--         `on` (\(rwd :& sa) -> rwd ^. DB.RewardAddrId ==. sa ^. DB.StakeAddressId)
--           `innerJoin` table @DB.Withdrawal
--         `on` (\(rwd :& _sa :& wdrl) -> rwd ^. DB.RewardAddrId ==. wdrl ^. DB.WithdrawalAddrId)
--     groupBy (sa ^. DB.StakeAddressId)
--     let sumReward = sum_ (rwd ^. DB.RewardAmount)
--         sumWithdraw = sum_ (wdrl ^. DB.WithdrawalAmount)
--     having (sumReward <. sumWithdraw)
--     pure (sa ^. DB.StakeAddressView, sumReward, sumWithdraw)
--   pure $ List.sort (map convert res)
--   where
--     convert :: (Value Text, Value (Maybe Micro), Value (Maybe Micro)) -> AddressInfo
--     convert (Value saView, rwdTotal, wdrlTotal) =
--       AddressInfo
--         { aiStakeAddress = saView
--         , aiSumRewards = DB.unValueSumAda (Just rwdTotal)
--         , aiSumWithdrawals = DB.unValueSumAda (Just wdrlTotal)
--         }
