name: Check HLint

on:
  push: {}
  merge_group: {}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Set up HLint
        uses: rwe/actions-hlint-setup@v1.0.3
        with:
          version: "3.2.7"

      - name: Run HLint
        uses: rwe/actions-hlint-run@v2.0.1
        with:
          path: "."
          fail-on: error


